name: Docker Image CI

on:
  push:
    tags:
      - v1.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKERHUB_TESTAPP }}
          tags: |
            type=semver,pattern={{version}}

      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ vars.DOCKERHUB_TESTAPP }}:latest

      - name: Check kuberentes cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: cluster-info

      - name: Deploy to kuberentes cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment/testapp nginx=${{ steps.meta.outputs.tags }}