name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKERHUB_TESTAPP }}
          tags: |
            type=sha,format=short,prefix=

      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ vars.DOCKERHUB_TESTAPP }}:latest