name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ vars.DOCKERHUB_TESTAPP }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha,format=short,prefix=

      - uses: actions/checkout@v4
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag antonmayko/nginx:$(date +%s)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ vars.DOCKERHUB_TESTAPP }}:latest